name: App CI/CD On Push - Main

on:
  push:
    branches:
      - main
    

jobs:
  build-and-deploy:
    runs-on:
      - ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.7'
        bundler-cache: true
        working-directory: 'app/android'