name: Backend CI/CD On Push
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
        
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: expense-tracker-backend
      REGISTRY: ghcr.io
      REPO_OWNER: pvico12
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ gitea.actor }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    
    - name: Build and Push Docker image
      run: |
        cd analytics
        docker build -t ${REGISTRY}/${REPO_OWNER}/${IMAGE_NAME}:latest .
        docker push ${REGISTRY}/${REPO_OWNER}/${IMAGE_NAME}:latest
